### ISSUE TITLE
The cpsyexam_qa dataset is missing

### ISSUE THREAD

**Issue by Rickwang0** [CAS-SIAT-XinHai/CPsyExam#2]
Hello, I noticed that your paper mentions the cpsyexam_QA dataset and the file path "evaluations/llmeval/cpsyexam/cpsyexam_qa" in the evaluate_qa function section. However, I couldn't find the QA dataset in the "CPsyExam/evaluations/llmeval/cpsyexam" directory of this GitHub repository. Could you please upload the cpsyexam_qa dataset?

**Comment by BestLemoon** [comment]
Thanks for your reminder. I have uploaded the qa dataset, enjoy it.
